#!/usr/bin/perl

use strict;
use warnings;
use Data::Dumper;

my ($filename) = @ARGV;
die "no $filename" unless -f $filename;

my $text = `unrtf --text '$filename' | grep -v '^###'`;
print "got " . length($text) . " characters\n";

my @lines = split(/\n/,$text);
my @newlines;

my $continue_flag;
foreach my $line (@lines) {
	next if $line =~ /^Printed on/;
	next if $line =~ /^Range/;
	next if $line =~ /^DOWNLOAD REPORT/;
	next if $line =~ /^by touch/;
	next if $line =~ /^Deggy Corp/;
	next if $line =~ /^Touch date/;
	next if $line =~ /^Description/;
	next if $line =~ /^\d+ of \d+/;
	next if $line =~ /^[- ]*$/;
	next if $line =~ m{^\d+/\d+/\d+ - \d+/\d+/\d+};

	if ($line =~ /^Pen download/) {
		$continue_flag = 1;
		push(@newlines,$line);
	} elsif ($continue_flag) {
		$newlines[ scalar( @newlines ) - 1 ] .= $line;
		$continue_flag--;
	} elsif ($line =~ /[AP]M[ ]*$/) {
		if ($line =~ /[ ]*$/) {
			$continue_flag = 1;
		} else {
			$continue_flag = 0;
		}

		if ($line =~ /AM[ ]*$/) {
			$line =~ /(\d+):(\d+):(\d+) AM/;
			my($h,$m,$s) = ($1,$2,$3);
			$h = 0 if $h == 12;
			my $newtime = sprintf("%02u:%02u:%02u", $h, $m, $s);
			$line =~ s/(\d+):(\d+):(\d+) AM/$newtime/;
		}

		if ($line =~ /PM[ ]*$/) {
			$line =~ /(\d+):(\d+):(\d+) PM/;
			my($h,$m,$s) = ($1,$2,$3);
			$h += 12 unless $h == 12;
			my $newtime = sprintf("%02u:%02u:%02u", $h, $m, $s);
			$line =~ s/(\d+):(\d+):(\d+) PM/$newtime/;
		}

		push(@newlines,$line);
	} elsif ($line =~ /^Customer.Site/) {
		$continue_flag = 1;
		push(@newlines,$line);
	} else {
		push(@newlines,$line);
	}
}

print "\n\n----------------------begin-redone-----------------\n";
print join("\n",@newlines);
print "\n\n";
